config = {}

config["RECAPTCHA_SITE_KEY"] = "6LcEwXIUAAAAAImsYjyZlhAzbIgNlFUOnZr5fp7N"
config["RECAPTCHA_SECRET"] = "6LcEwXIUAAAAALJAISulJ7KD-9bGHMk64kB--4a3"

config["SESSION_KEY"] = "MAKE_ME_RANDOM"


config["VIEW_CONFIG"] = {}

config["VIEW_CONFIG"]["NAME"] = "Dan"
config["VIEW_CONFIG"]["RECAPTCHA_SITE_KEY"] = config["RECAPTCHA_SITE_KEY"]
